name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily to check for upstream updates, adjust as necessary

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history to ensure all branches are available

    - name: Set Git user
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "you@example.com"

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout main and rebase
      run: |
        git checkout main
        git pull --rebase upstream main  # Rebase main with upstream

    - name: Checkout changes branch
      run: git checkout changes

    - name: Rebase changes onto main
      run: git rebase main

    - name: Push rebased changes branch
      if: success()
      run: |
        git push origin changes --force

  deploy:
    needs: rebase
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myapp:${{ github.sha }} .

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_USERNAME }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag myapp:${{ github.sha }} myusername/myapp:latest
        docker push myusername/myapp:latest

    - name: Deploy to server
      run: |
        ssh user@your-server "docker pull myusername/myapp:latest && docker-compose up -d"
